#pragma config(Sensor, S1,     leftTouch,      sensorEV3_Touch)
#pragma config(Sensor, S2,     rightTouch,     sensorEV3_Touch)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int highPowerMin = 75;
	int highPowerMax = 100;
	int lowPowerMin = 40;
	int lowPowerMax = 60;
	srand(nSysTime);
	while (true)
	{
		// Turn the LED red if the touch sensor is pressed
		if (getTouchValue(S1) == 1 && getTouchValue(S2) == 1)
		{
			setLEDColor(ledRed);
			motor[motorA] = -(random(highPowerMax-highPowerMin) + highPowerMin);
			motor[motorB] = -(random(highPowerMax-highPowerMin) + highPowerMin);
			sleep(1000);
		}
		else if (getTouchValue(S1) == 1)
		{
			setLEDColor(ledRed);
			motor[motorA] = -(random(lowPowerMax-lowPowerMin) + lowPowerMin);
			motor[motorB] = -(random(highPowerMax-highPowerMin) + highPowerMin);
			writeDebugStreamLine("%d, %d", motor[motorA], motor[motorB]);
			sleep(1000);
		}
		else if (getTouchValue(S2) == 1)
		{
			setLEDColor(ledRed);
			motor[motorA] = -(random(highPowerMax-highPowerMin) + highPowerMin);
			motor[motorB] = -(random(lowPowerMax-lowPowerMin) + lowPowerMin);
			sleep(1000);
		}
		// If it's in a released state, turn the LED green
		else
		{
			// Drunken Sailor Walk will go here
			setLEDColor(ledGreen);
			motor[motorA] = random(highPowerMax-highPowerMin) + highPowerMin;
			motor[motorB] = random(highPowerMax-highPowerMin) + highPowerMin;
			sleep(250);
		}
		//Loop to monitor value in Sensor debugger window
		sleep(50);
	}
}
